### PR TITLE
fix: change libcluster strategy from Kubernetes.DNS to Kubernetes

### PR DESCRIPTION
**Pull request by shiipou**
Signed-off-by: shiipou <shiishii@nocturlab.fr>

### CODE REVIEW

**Comment by pichoemr** [comment]
More info in the description ?

**Comment by shiipou** [comment]
> More info in the description ?

Oh, that strange this one is not merged.

We call the DNS to find all pods behind the kubernetes service, the PR change that to call the Kubernetes API to find the pods ip in the cluster.

**Review by taorepoara — APPROVED** [review]
I change the PR name to something clearer

**Review by taorepoara — APPROVED** [review]

**Pull request merged**
