### PR TITLE
fix: Add mac M1 docker image

### LINKED ISSUE #366: [Bug]: Mac M1 docker image not available
### What happened?

When i try to pull the lenra/server:beta, i got an error.
The Mac M1 ARM64 image does not seems to exists. 

### What browsers are you seeing the problem on?

Other (specify above)

### Version

beta

### Relevant log output

```Shell
❯ docker pull lenra/server:beta
beta: Pulling from lenra/server
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### PR DESCRIPTION
**Pull request by Nesqwik**
Closes #366

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [x] I made my own code-review before requesting one

## Description of the changes
I just added the linux/arm platform to the docker build command. This should ask buildx to build for arm architectures.

### CODE REVIEW

**Comment by Nesqwik** [comment]
In fact, we removed the arm build because of a bug that happend previously when building the image : 

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped error.
```

Apparently nothing we can do. I'll try some fix but i doubt we can fix it easily.

**Review by taorepoara — APPROVED** [review]

**Pull request merged**
