### PR TITLE
feat: Manage not authenticated users

### LINKED ISSUE #539: Permit socket connection without OAuth2 token
## What should be done 

Allow the user to connect to the websocket with OAuth2 token. A user without token will have the role `guest`.

## Technical recommandation

To manage not authenticated users on have many task to manage:

- [x] Get the routes roles list from the manifest
- [x] Get the user role from the websocket connection
- [x] Filter the routes given to the client based on the user role

## Ecological concerns

Check that the cache is not based on the user role (only if defined in the context, but managed later).

### PR DESCRIPTION
**Pull request by taorepoara**
## About this PR

Closes #539 

## Technical highlight/advice
I made a channel test case that made me create many files...

## How to test my changes
- Create an app with routes available for guest users (see https://github.com/lenra-io/api/issues/15)
- Start it (with JSON view since Lenra view need a client adaptation)

## Checklist
- [ ] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by taorepoara** [comment]
@jonas-martinez Can you look if you can fix the unit tests ?

**Comment by jonas-martinez** [comment]
@taorepoara The unit tests are working. Maybe you wanted to fix the CI instead ? I'm working on it.

**Review by jonas-martinez — APPROVED** [review]
LGTM

We will need to fix the tests later, I linked a new issue just for that.

**Pull request merged**
