### PR TITLE
fix: @lenra system listeners like @lenra:navTo

### PR DESCRIPTION
**Pull request by taorepoara**
## About this PR
Fix the `@lenra:navTo` system listener.

## How to test my changes
Set the server branch in the `server/mix.exs` of the [devtool](https://github.com/lenra-io/devtool):

```elixir
ref: "debug-devtool"
```

Get the deps and build the devtool Docker image:

```bash
cd server
mix deps.get
cd ..
docker build -t lenra/devtools:local .
```

Try an app that uses `@lenra:navTo` like https://github.com/lenra-io/app-camping-des-speakers (be careful of the branch depending on this merge https://github.com/lenra-io/app-camping-des-speakers/pull/38).

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by jonas-martinez — APPROVED** [review]
I have no words 🥲 Nice catch ! Looks good to me !

**Comment by taorepoara** [comment]
> I have no words 🥲 Nice catch ! Looks good to me !

You gave me the solution on friday ;-)

**Pull request merged**
