### PR TITLE
fix: Error handling in OAuth

### PR DESCRIPTION
**Pull request by jonas-martinez**
## About this PR

Linked to https://github.com/lenra-io/server/issues/399

I added some error handling on the oauth system. If the user fetched from the token is nil, we return a invalid_token error.

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by taorepoara** [comment]
@jonas-martinez Can you explain this PR, I don't understand (even reading the linked issue) when that happen.

You also have to fix the checks

**Comment by jonas-martinez** [comment]
@taorepoara I added some text in the PR description to explain its purpose.

**Review by taorepoara — COMMENTED** [review]
Seems OK, but the CI is failing

**Comment by jonas-martinez** [comment]
@taorepoara Fixed

**Pull request merged**
