### PR TITLE
fix: build status

### PR DESCRIPTION
**Pull request by pichoemr**
## About this PR

Closes # 

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by shiipou — APPROVED** [review]

**Comment by shiipou** [comment]
@pichoemr You must resolve the conflict and then you can squash merge it.

**Review by taorepoara — APPROVED** [review]
Seems OK. Have try it ?

**Comment by pichoemr** [comment]
> Seems OK. Have try it ?

Yes we test it in staging

**Pull request merged**
