### PR TITLE
feat: Login and register forms style

### LINKED ISSUE #388: [Task] Implement the Login/Register page Design
[See Figma Auth design](https://www.figma.com/file/1TeGq312pT4ZIiRn5u6iYU/03_ipsoon%26lesdevs?type=design&node-id=1093-14625&t=90OCyXTAXO3umyjY-0)

### PR DESCRIPTION
**Pull request by taorepoara**
Closes #388 

## Description of the changes
Add style to the login and register forms.

I've only implemented the client page since we need more OAuth features to work on back-office and app pages since we need to know which client is calling the page.

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [x] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [x] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

## Technical highlight/advice
Since the password is managed by a different table than the user, we need to adapt the login password field make it work in both situations.

### CODE REVIEW

**Review by jonas-martinez — CHANGES_REQUESTED** [review]
check above comment

**Review by Nesqwik — CHANGES_REQUESTED** [review]
Some visual issues : 
- The ">" is wrongly placed and incorrectly colored according to figma
Capture d’écran 2023-07-13 à 11 34 04

- The form shift up/down entirely when switching from "login" to "register"
Enregistrement de l’écran 2023-07-13 à 11 37 32

- when reducing the screen height, the scroll appear vertically **AND** horizontally instead of vertically only.
Enregistrement de l’écran 2023-07-13 à 11 47 01



I've reproduced all of them in Arc Browser (Chrome-based) and Firefox.

**Comment by taorepoara** [comment]
>     * The ">" is wrongly placed and incorrectly colored according to figma
>       Capture d’écran 2023-07-13 à 11 34 04

I've resolved this issue in another branch. I let it like that.

>     * The form shift up/down entirely when switching from "login" to "register"
>       Enregistrement de l’écran 2023-07-13 à 11 37 32

This is the wanted behavior: the content is vertically centered in the page as it is in Figma.

>     * when reducing the screen height, the scroll appear vertically **AND** horizontally instead of vertically only.
>       Enregistrement de l’écran 2023-07-13 à 11 47 01
> 
> 
> I've reproduced all of them in Arc Browser (Chrome-based) and Firefox.

I could not reproduce this problem in Chrome nor Firefox. We'll check it again in the next branch.

**Comment by Nesqwik** [comment]
> This is the wanted behavior: the content is vertically centered in the page as it is in Figma.

Well.. This should not IMO :( 
 
> I could not reproduce this problem in Chrome nor Firefox. We'll check it again in the next branch.

It probably depends of the screen size ? I have a small 13" screen

**Pull request merged**
