### PR TITLE
build(application_runner)!: Change config url to internal_api_url

### LINKED ISSUE #434: Rename the `url` config variable
# BREAKING CHANGE

## What should be done 
The naming of this variable is not self-explanatory, this should be changed to be more precise such as `api_url`

### PR DESCRIPTION
**Pull request by shiipou**
## About this PR

Closes #434 

This PR rename the config url from application runner to internal_api_url so it's more clear to know what it do.

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by shiipou** [comment]
@jonas-martinez @pichoemr Can you test this to be sure nothing break ? I didn't find out myself how to test it on my local env.
If you didn't know I can test on staging.

**Comment by jonas-martinez** [comment]
I'm not sure whether the changes would break anything, I'll see tomorrow with @pichoemr .

**Comment by shiipou** [comment]
> I'm not sure whether the changes would break anything, I'll see tomorrow with @pichoemr .
@jonas-martinez 
That can break current devtool config, but it only need to change the config.ex file. Nothing more I think.

**Review by jonas-martinez — APPROVED** [review]

**Pull request merged**
